[package]
name = "k8s-device-plugin-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
description = "Core traits and types for Rust Kubernetes device-plugin and DRA drivers"
readme = "README.md"


[dependencies]
async-trait.workspace = true
thiserror.workspace = true


[dev-dependencies]
tokio = { workspace = true, features = ["rt"] }


[lints]
workspace = true
