[package]
name = "k8s-device-plugin-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Core traits and types for Rust Kubernetes device-plugin and DRA drivers"
readme = "README.md"


[features]
resource-health = ["dep:tokio"]


[dependencies]
async-trait.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"], optional = true }


[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["rt"] }


[lints]
workspace = true
