[package]
name = "k8s-device-plugin"
description = "Unified Rust entrypoint for Kubernetes device-plugin and DRA runtimes"
readme = "README.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true


[dependencies]
k8s-device-plugin-core.workspace = true
k8s-device-plugin-dra = { workspace = true, optional = true }
k8s-device-plugin-lib = { workspace = true, optional = true }
k8s-device-plugin-proto = { workspace = true, optional = true }


[features]
default = ["device-plugin", "dra", "proto"]
device-plugin = ["dep:k8s-device-plugin-lib"]
dra = ["dep:k8s-device-plugin-dra"]
proto = ["dep:k8s-device-plugin-proto"]
resource-health = [
    "dra",
    "k8s-device-plugin-core/resource-health",
    "k8s-device-plugin-dra/resource-health",
]


[lints]
workspace = true
