[package]
name = "k8s-device-plugin-lib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Kubernetes device-plugin server runtime for Rust"


[dependencies]
hyper-util.workspace = true
tokio = { workspace = true, features = ["fs", "time"] }
tokio-stream.workspace = true
tonic.workspace = true
tower.workspace = true
tracing.workspace = true

k8s-device-plugin-core.workspace = true
k8s-device-plugin-proto.workspace = true


[dev-dependencies]
k8s-device-plugin-test.workspace = true
prometheus_exporter.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing-subscriber.workspace = true


[lints]
workspace = true
