[package]
name = "k8s-device-plugin-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Generated Kubernetes device-plugin and DRA protocol bindings for Rust"
readme = "README.md"


[features]
dra = []
dra-health = ["dra"]


[dependencies]
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true


[build-dependencies]
tonic-prost-build.workspace = true

# [lints]
# workspace = true
