apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-device-plugin-dra-example

resources:
  - namespace.yaml
  - rbac.yaml
  - daemonset.yaml

images:
  - name: k8s-device-plugin-dra-example
    newName: k8s-device-plugin-dra-example
    newTag: latest
