apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-device-plugin-dra-example
  namespace: k8s-device-plugin-dra-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-device-plugin-dra-example
rules:
  - apiGroups: ["resource.k8s.io"]
    resources: ["resourceclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["resource.k8s.io"]
    resources: ["resourceslices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-device-plugin-dra-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-device-plugin-dra-example
subjects:
  - kind: ServiceAccount
    name: k8s-device-plugin-dra-example
    namespace: k8s-device-plugin-dra-example
